receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "otel-collector:4317"
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
